### ISSUE TITLE
Expression: label readability and guidance on max data size

### ISSUE THREAD

**Issue by davidarndt** [sbabicki/heatmapper#45]
Increase font size so it is readable on large data sets. Pick a maximum vertical dimension, and from that determine the maximum number of rows that will still allow labels to be readable. Set things so that the number of rows is reasonable compared to what we might expect users to submit.

**Comment by davidarndt** [comment]
See also issue #11 (option to resize labels).

**Comment by yongjiel** [comment]
Resizing the image of heatmap.2 is done. Now the labels are visible, but the heatmap image is inevitably  bigger to coop the row's height with the labels. Tested with 3 examples and input files. All are fine.

**Comment by yongjiel** [comment]
Now, the label is scalable now.  If each row's pixels number is too small,  the font size will be 1 (proportional to the default size); if each row's pixels number is higher than 13 pixels, the font size will increase proportional to the each row's pixels, but font size maximum is 1.45; if each row's pixels still increases, font size still keeps maximum 1.45.
