### ISSUE TITLE
Pairwise: add different distance measures for distance matrix

### ISSUE THREAD

**Issue by davidarndt** [sbabicki/heatmapper#50]
This was not specifically requested by any reviewers, but is necessary if we want to add the ability to compare multiple matrices that each use different distance measures. The distance measures from Expression could be moved over for use in Pairwise.

**Comment by yongjiel** [comment]
Plugged in the distance selection box and it cooperates with radio selection of 'Calculate distance matrix' in ui.R. In the server.R, added  in the code as the same code of calculating distances as in expression/server.R and some fixes on some functions. Now the different distances of matrixes works fine for input files and example files.
