### ISSUE TITLE
Image Overlay: add legend to grid plot

### ISSUE THREAD

**Issue by davidarndt** [sbabicki/heatmapper#66]

**Comment by yongjiel** [comment]
After I updated to the newest recent version of master branch, the image overlay part did not work fine with  example loading.  It always gives me this error message: Warning: Error in kde2d.weighted: argument "w" is missing, with no default. 
I just wonder who followed this part before.

**Comment by yongjiel** [comment]
Hi, David:

After I updated to the newest recent version of master branch, the image
overlay part did not work fine with example loading. It always gives me
this error message: Warning: Error in kde2d.weighted: argument "w" is
missing, with no default.
I just wonder who followed this part before.

Regards,
Jack

**Comment by davidarndt** [comment]
I get a different error: cannot coerce type 'closure' to vector of type 'character'.
I can get around the error by selecting Custom for Colour Scheme.

**Comment by davidarndt** [comment]
The bug is fixed.

**Comment by davidarndt** [comment]
Done.
