### ISSUE TITLE
Expression: Error message with some distance measurement methods

### ISSUE THREAD

**Issue by Pscott4** [sbabicki/heatmapper#85]
I am getting the error message 
"Unexpected validation result: Error in UseMethod("as.dendrogram"): no applicable method for 'as.dendrogram' applied to an object of class "logical"

ERROR:  Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent

File could not be read. Please ensure that the file you uploaded is valid.

I get this any time I use a distance measure other than euclidian. I've tried reformating the files but it doesn't work right. It works with the example files just not with mine.

**Comment by yongjiel** [comment]
Please check this link to see the format of input file.
http://heatmapper.ca/about/instructions/

**Comment by Pscott4** [comment]
I think it is properly formatted as a tab separated .txt file, one header row, one column with names. It displays in the table properly. And if it didn't accept the file then why would it work with euclidian?
<img width="906" alt="screen shot 2018-07-05 at 8 19 23 pm" src="https://user-images.githubusercontent.com/26771439/42354002-dc3436b2-8091-11e8-880c-39fdcf840cdb.png">


[Rice Log2 FC.txt](https://github.com/WishartLab/heatmapper/files/2168634/Rice.Log2.FC.txt)

**Comment by yongjiel** [comment]
File format should look like thus.


Please check out the link http://www2.heatmapper.ca/about/instructions/.

**Comment by RemPsyc** [comment]
Looking at your data, I think I know the source of your problem. I had the same issue. I’ve actually spent several days pulling my hair tying to figure this out before finding out that heatmapper will not accept values smaller than 0... the solution was to multiply all my values by 100 to make sure there was not a single value below 0... and this immediately fixed the issue for me. As stupid as that. It’s been a few months but I’m pretty sure that’s the issue for you too. Try it and let us know if it worked.

Rémi

Le 5 juill. 2018 à 20:27, Pscott4 <notifications@github.com<mailto:notifications@github.com>> a écrit :


I think it is properly formatted as a tab separated .txt file, one header row, one column with names. It displays in the table properly. And if it didn't accept the file then why would it work with euclidian?
[screen shot 2018-07-05 at 8 19 23 pm]<https://user-images.githubusercontent.com/26771439/42354002-dc3436b2-8091-11e8-880c-39fdcf840cdb.png>

Rice Log2 FC.txt<https://github.com/WishartLab/heatmapper/files/2168634/Rice.Log2.FC.txt>

**Comment by davidarndt** [comment]
The issue is that the 'UNIQID' column is required. Negative values will not prevent things from working.
