### ISSUE TITLE
Image Overlay Error: Disconnected from server on clicking for co-ordinates on the image

### ISSUE THREAD

**Issue by sreejakshetty** [sbabicki/heatmapper#88]
On clicking on the image, it is showing disconnected from server. Is this a server issue or a code bug. Could anyone tell us how to fix it?
Thank you!
![screenshot from 2018-09-20 16 04 23](https://user-images.githubusercontent.com/14835922/45812958-f268e880-bcee-11e8-9a0a-85656a0912cf.png)

**Comment by davidarndt** [comment]
This would be a server issue, and happens whenever the Shiny server stops or restarts for whatever reason. I have restarted Shiny so hopefully things will be working again. Let us know if you have any further issues.
